### ISSUE TITLE
Menu bar in SaltGUI

### ISSUE THREAD

**Issue by erwindon** [maerteijn/SaltGUI#20]
I want to split the recent additions for keys-management to a separate page.
First page would then be the traditional minions overview.
Second page would then be the recent keys-management page.
And there would be room for a few more pages as needed.
So, a simple menu bar is needed to select between the pages.

Could look like this:

![saltgui_menu](https://user-images.githubusercontent.com/3663742/40807662-3d48c36a-6525-11e8-84ff-222e4dbb5aca.png)

any objections, improvements, etc?

**Comment by maerteijn** [comment]
This would indeed be a pretty nice improvement. The styling of the menu looks fine to me like this!

**Comment by maerteijn** [comment]
@erwindon , there is something here that I should mention which I don't know (yet) how to solve, so let's put my thoughts here and see what you think.

Until now, SaltGUI was also responsive, and did a pretty good job with that:

<img width="334" alt="responsive" src="https://user-images.githubusercontent.com/121401/43128756-1996b250-8f33-11e8-9995-999ed26a298b.png">

I like that, because I'm pretty sure this application is (or will be) used on phones/tablets as well.

But with the introduction of the menu, this will become a lot more difficult without any kind of hamburger menu or so:

<img width="320" alt="responsive_with_menu" src="https://user-images.githubusercontent.com/121401/43128798-2deb4dc4-8f33-11e8-8737-cfd10892e74f.png">

This will become worse when we add more menu-items. Also, the css files become bigger and bigger, so fixing this will be harder with each improvement we add.

And then we are not talking about all the functionality you have waiting in your feature branches.

And I don't want SaltGUI to become a hard, unmaintainable project.

So, or we should fix the css for this. But I'm not a super css hero actually. I'm doing this project for fun, to learn, and because I promised the original author to take good care of SaltGUI. Doing css stuff which has been done 100 times before with bootstrap / foundation / bulma feels stupid to do.

So maybe we should think about introducing a css framework here (I like bulma for it's simplicity) and do a complete restyling  with that. Which also means we can use all it's components which are pretty nice. Which also means it takes some time to do this and that it will take more time for your other features to be merged.

We could also do some quick hacks first: disable the menu on a small resolution and some css fixes here and there and then move on to the bulma approach. Which makes more sense when you think the scrum way.

So now I put this all on the table, your thoughts please :)

**Comment by erwindon** [comment]
I can't use this application on my phone as my company- and/or customer-policy does not allow it (and they are right). So for me it is always a relatively big screen, typically 1920x1200 or so, and often in dual monitor setup. But I fully agree on a responsive design. I did notice the `@media` clauses in the css files, but there was no other mention of responsive design and/or support for smaller devices. So it did not get much of my attention.
I see no CSS explosion happening. And any new CSS for any of the new pages is properly separated. My biggest concern on the code is the manipulation of elements, which could benefit from e.g. JQuery.
I'll configure my browser to be able to switch to 800px or 1200px and always test with that too.
I'll also redesign the css for the menu-bar on small screens to show as a separate bar below the logo/logout/run fields. Even with all of the other PRs, that should fit. And otherwise it can simply flow on 2 text lines. Or indeed a hamburger-menu. That can be a regular dropdownmenu. I'll put the logout button there tool.
Below 800px, the screen is single column full width. But what is the desired effect for screens 800..1200px?

**Comment by maerteijn** [comment]
Ok, thank you for your insight. I spend some time investigating the css and how this responsive thing works and it's not complicated at all. See my comments on #31 as well

**Comment by erwindon** [comment]
> Below 800px, the screen is single column full width.
> But what is the desired effect for screens 800..1200px?
As there exists both a `@media(max-width: 1200px)` and a `@media(max-width: 800px)`.
And currently I don't know what to test for when between these screen widths.
Can you help me with this question?

**Comment by maerteijn** [comment]
Well, I just committed 67802b83014c07e4212d622724b0ba8892602f1c to the `hamburger` branch which removes this 1200px media selector and somehow made the run-command button less jumpy.

I would say for now this is sufficient: SaltGUI looks fine now in all resolutions and making the distinction between mobile / desktop is fine enough for me (for now). Do you agree?

**Comment by maerteijn** [comment]
Merged and released
