### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by babs** [maerteijn/SaltGUI#26]
Hi,

It would be great to have a config file somehow, every time I want to update, I have to patch the code to switch eauth from pam to ldap :/
Is would be nice to store it somewhere once and for all.

**Comment by erwindon** [comment]
Can you please show what the exact changes are?
Is it only the {{eauth}} value in {{api.js|}?
And anything else than the changes in section {{external_auth}} in {{/etc/salt/master}}?

The allowed values seem to come from {{/usr/lib/python3.4/site-packages/salt/auth}}.
Just tested it with "auto". That seems to work fine.

My proposal would be to provide a dropdown box with all the known eauth methods and use the selected value. The selected value can be stored in a cookie, so that you do not have to update the dropdown box each time.

**Comment by erwindon** [comment]
With a bit of experimentation, it is now clear.
I've issued PR #27 for this.

**Comment by maerteijn** [comment]
Hi @babs 

I just merged #27  which allows you to select the login method. Could you test this with your LDAP setup to see if it works for your scenario?

**Comment by babs** [comment]
it works, but LDAP is not experimental :D

**Comment by erwindon** [comment]
LDAP was experimental because no-one had tested it yet with SaltGUI. I did not setup (or find) a working LDAP server to do that. Now that you have tested it, I've updated the GUI and issued a PR for that.

**Comment by babs** [comment]
oh, Ok :D
